### ISSUE TITLE
Multi-client Ecosystem Support

### ISSUE THREAD

**Issue by eugenefine** [polywrap/technical-council#2]
### Determine:
- How will the development process for a new client look like
- How will the maintenance of multiple clients look like
- How will we track the supported and unsupported features across clients, and their versioning
- Creation of a roadmap of clients to have in the future
- What is the MVP for a Polywrap client

#### Multi-Client Test Harness
- Generic way of invoking clients in all languages
- The ability to introspect traces from these clients
- Known good set of responses & traces for each test in the suite

#### Adding A New Client To The Test Suite
- Client implementers would publish their `ClientServer` implementation (to DockerHub for example)
- They'd submit a PR, adding their image's name to a list of "known `ClientServer`s"

#### Generic Invocation
Each client would implement a `ClientServer`, which is a standardized HTTP API for creating & invoking Polywrap client instances.

```typescript
id = request(
  "https://client-server.io/api/v0/create-client"
  {
    plugins: ["plugin/filesystem"]
  }
)

resp = request(
  "https://client-server.io/api/v0/invoke"
  {
    client: id,
    uri: "ens/plugin-test.eth",
    method: "writeFileTest",
    tracing: `https://tracing-server.io/${id}`
  }
)

expect(resp).toEqual(goodResp);

trace = request(
  `https://tracing-server.io/${id}/get`,
  {
    trace: resp.trace
  }
)

expect(trace).toContain(goodCallstackTrace)
```

#### Generic Tracing
The Polywrap JS Client currently has support for OpenTelemetry standardized tracing. This is something that is readily available in other langauges, and gives us a standard for trace logging.

We would need to define our "known good traces", letting client implementers know what the order-of-operations are for the client's internal operations.

#### Other Reference Projects
https://www.godaddy.com/engineering/2021/06/14/test-harness/

## Action Items
- [x] Define Description
- [x] Select Priority
- [ ] Select Products
- [ ] Select Qualities  
- [ ] Specification
- [ ] General Brainstorming & Feedback

**Comment by namesty** [comment]
https://hackmd.io/@kXW7IfLbTSigRA3FFTFNbA/r1UfE2a79/edit

**Comment by jbinter** [comment]
Related Proposals that should be pursued in parallel

Pythong Client Proposal - [](https://forum.polywrap.io/t/2022-05-2022-06-2022-07-grant-proposal-pwv/279)
Rust Client WIP - [](https://github.com/polywrap/monorepo/tree/feat/rust-package/packages/rs)

**Comment by dOrgJelli** [comment]
Moving this issue here: https://github.com/polywrap/toolchain/issues/1202
