### ISSUE TITLE
Polywrap Integration Testing Framework

### ISSUE THREAD

**Issue by eugenefine** [polywrap/technical-council#3]
## Description
- A good specification and testing framework for the end-to-end integration testing for any wrapper or plugins 
- Should be extensible enough to extend support to multiple clients in the future. (relates to multi-client test harness)  

## Proposed Architecture

We should use recipes and cookbooks to not only run test cases but also validate the output. For that, we need a language that not only supports schema type but also constraints and yet should be easy to read and understand. From my research, I found that `cuelang` crosses all the required fields. 

With `cuelang`, we can write expected output constraints in the recipe itself and validate against it after each run. 

Here's the example of how a recipe written in `cuelang` would look like:
```cue
package simplePrice

[
	{
		api: "ens/testnet/coingecko.eth"
	}, {
		query: "./schema.graphql"
		variables: {
			ids: ["ethereum", "solana"]
			vs_currencies: ["usd", "btc"]
			include_market_cap:      false
			include_24hr_vol:        false
			include_24hr_change:     false
			include_last_updated_at: true
		}
		output?: {
			#PriceData: {
					vs_currency: "usd" | "btc"
					price: >="0"
					market_cap: >="0" | null
					vol_24h: >="0" | null
					change_24h: >="0" | null
			}
			#SimplePrice: {
					id: "ethereum" | "solana"
					price_data: [...#PriceData]
					last_updated_at: >="0" | null
			}
			data: {
				simplePrice: [...#SimplePrice]
			}
		}
	}]

```

## Action Items
- [x] Define Description
- [x] Select Priority
- [x] Select Products
- [x] Select Qualities  
- [ ] Specification
- [ ] General Brainstorming & Feedback

**Comment by jbinter** [comment]
Initial implementation complete. This will remain open for features to be included after Alpha release.

**Comment by dOrgJelli** [comment]
I'd like to actually close this, as we've successfully been able to move from conceptualization -> implementation. This to me is all the TC should be concerned with stewarding. In the future we may want to add this feature to the standard, which we can create a new tracking issue for.
