### ISSUE TITLE
Pre-Origin Schema Build Artifact

### ISSUE THREAD

**Issue by eugenefine** [polywrap/technical-council#5]
## Description
Currently, the schema build artifact that's within the wasm wrapper package is a GraphQL file. For example:
https://ipfs.io/ipfs/QmQhXyMLvxbKPmZ2RzMJMeHTx5saUfHzZmVR9LDVJaB8Zq

Storing the schema using GraphQL has the following limitations:
- **Inefficient**: Requires multi-step, complex, parsing to occur in order for the resulting `TypeInfo` to be created.
- **Portability**: GraphQL parsers are not very prevalent, and may not be available in a particular language.
- **Compatibility**: If features are added/removed from the schema, it is hard to make parsing forward/backward compatible.

Instead I propose that we replace the `schema.graphql` file with a `JSON` file, which contains `TypeInfo` (or something similar) reducing the number of translation steps the client has to do when parsing & using the file at run-time.

## Action Items
- [x] Define Description
- [x] Select Priority
- [x] Select Products
- [x] Select Qualities  
- [ ] Specification
- [ ] General Brainstorming & Feedback

**Comment by jbinter** [comment]
Link for the document from the 6/24/22 working session.  https://hackmd.io/@zbs1CidlRU6NAc7CvPR28w/B1SvZFQ5q

**Comment by dOrgJelli** [comment]
I think we should actually close this issue for now, and open up new ones as the need arises. The implementation is already complete for the initial plan that was decided upon rapidly due to the need to release origin.
