### ISSUE TITLE
Restructuring Polywrap Manifest Filenames

### ISSUE THREAD

**Issue by jbinter** [polywrap/technical-council#52]
## Description
<html><body>
<h1>Current State</h1>
<p>Currently, Polywrap supports the following manifest files:<br>
<code>web3api.yaml</code>: Used for wasm wrapper &amp; interface projects.<br>
<code>web3api.plugin.yaml</code>: Used for plugin wrapper project.<br>
<code>web3api.app.yaml</code>: Used for application projects.<br>
<code>web3api.build.yaml</code>: Customizes the build processed used for wasm wrappers.<br>
<code>web3api.deploy.yaml</code>: Defines the deployment process used for wasm wrappers &amp; interfaces.<br>
<code>web3api.meta.yaml</code>: Defines metadata for a wasm wrapper (description, repository, icon, etc).<br>
<code>web3api.infra.yaml</code>: Defines custom docker containers used by the wrapper.</p>
<h1>
<a name="problem-2" class="anchor" href="https://forum.polywrap.io/t/restructuring-polywrap-manifest-filenames/278#problem-2"></a>Problem</h1>
<p>It is not clear which of these manifests are used to define a 
project, and which ones are “extensions” or “customizations” to that 
project.</p>
<h1>
<a name="solution-3" class="anchor" href="https://forum.polywrap.io/t/restructuring-polywrap-manifest-filenames/278#solution-3"></a>Solution</h1>
</body>
</html>  

[Design](https://hackmd.io/xQDRrBxJTfGerQGWm1FeLw)

## Action Items
- [x] Define Description
- [x] Select Priority
- [x] Select Products
- [x] Select Qualities  
- [x] Specification
- [x] General Brainstorming & Feedback

**Comment by nerfZael** [comment]
We could have the main manifest in each of the projects be: polywrap.yaml (wrap.json when built e.g. wasm)
Then extensions could be polywrap.build.yaml, polywrap.meta.yaml, etc.
I do not think it would be an issue to have the same name for essentially different formats/types of projects since there is only one main polywrap manifest per project.

**Comment by dOrgJelli** [comment]
Latest version viewable here: https://hackmd.io/xQDRrBxJTfGerQGWm1FeLw?both

**Comment by dOrgJelli** [comment]
Had a final review today, everything looks good: https://hackmd.io/xQDRrBxJTfGerQGWm1FeLw?view

Moving this to an issue to be added to the roadmap: https://github.com/polywrap/monorepo/issues/1057
